[build]
  publish = "dist"  # Point to the dist folder, not "build"
  command = "npm run build"  # This will run the build process to create the dist folder

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true  # Ensures all routes redirect to index.html for React Router

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"
