[build]
  publish = "build"  # This is the build folder created after running `npm run build`
  command = "npm run build"  # This runs the build process

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true  # Ensure that the redirect is always applied, even if the URL exists

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
